spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${FOORUN_EMAIL_USERNAME}
    password: ${FOORUN_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
